version: '3'
services:
    detection_app:
        build: ./detection_app
        ports:
            - "80:80"
        depends_on:
            - coco_model
    coco_model:
        image: alimaan/od_test:latest
